site_name: 생산운영과 공장관리
theme:
  name: material
  features:
    - content.action.edit
    - navigation.sections
    - navigation.indexes
    - toc.follow
repo_url: https://github.com/yeonkyupark/pepc3e
repo_name: yeonkyupark/pepc3e
edit_uri: edit/main/docs/

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - stylesheets/extra.css
  
nav:
  - Home: index.md

  - 1. 생산전략:
      - 1. 경쟁우위 생산전략: 0101_competitive_manufacturing_strategy.md
      - 2. 생산구조와 방식(Layout): 0102_production_structure_and_layout.md
      - 3. 구매와 외주전략: 0103_purchasing_and_outsourcing_strategy.md
      - 4. 인력과 직무설계: 0104_workforce_and_job_design.md
      - 5. 사업환경 분석: 0105_business_environment_analysis.md

  - 2. 생산운영 및 물류관리:
      - 1. 수요예측과 일정관리: 0201_demand_forecasting_and_scheduling.md
      - 2. 프로세스 진도관리: 0202_process_progress_control.md
      - 3. 공급망 관리: 0203_supply_chain_management.md
      - 4. 물류관리(자재 및 재고관리): 0204_logistics_material_and_inventory_management.md

  - 3. 공정관리:
      - 1. 생산계획수립: 0301_production_planning.md
      - 2. 공정설계: 0302_process_design.md
      - 3. 작업계획수립: 0303_work_planning.md
      - 4. 표준작업관리: 0304_standard_work_management.md
      - 5. 설비보전관리: 0305_maintenance_management.md
      - 6. 공정개선: 0306_process_improvement.md

  - 4. 설비관리:
      - 1. 설비계획 및 관리: 0401_facility_planning_and_management.md
      - 2. 자재취급 및 운반관리: 0402_material_handling_and_transport.md
      - 3. 환경관리 및 안전관리: 0403_environmental_and_safety_management.md
      - 4. 시설 및 유틸리티관리: 0404_facility_and_utility_management.md
      - 5. 공장자동화 기술: 0405_factory_automation_technology.md

  - 5. 작업 및 생산성과 측정과 개선:
      - 1. 작업방법 및 시간연구: 0501_work_method_and_time_study.md
      - 2. 프로세스 분석과 개선: 0502_process_analysis_and_improvement.md
      - 3. 생선성 관리: 0503_productivity_management.md
      - 4. 품질관리: 0504_quality_management.md

  - 6. 원가관리 및 경제성 공학:
      - 1. 사업성 분석: 0601_feasibility_analysis.md
      - 2. 원가관리: 0602_cost_management.md
      - 3. 가치공학: 0603_value_engineering.md
      - 4. 경영과학(OR): 0604_operations_research.md

  - 7. 생산지원기술 및 기타:
      - 1. 정보화활용기술(스마트팩토리 등): 0701_information_technology_and_smart_factory.md
      - 2. 제품개발기술: 0702_product_development_technology.md
      - 3. 서비스운영관리: 0703_service_operations_management.md
      - 4. 생산혁신기술: 0704_production_innovation_technology.md
      - 5. 공장관리에 관한 신기술 및 경향에 관한 사항: 0705_emerging_factory_management_technologies_and_trends.md
